baseURL = "https://ajulu.netlify.app/"
languageCode = "en-us"
title = "Stephen Ajulu"
theme = "aju-hub"
paginate = 24
copyright= "Stephen Ajulu."
timeZone = "Africa/Nairobi"

[outputs]
home = ["HTML", "RSS", "JSON", "SEARCH_JSON"]
section = ["HTML", "RSS", "JSON"]
taxonomy = ["HTML", "RSS", "JSON"]
term = ["HTML", "RSS", "JSON"]

[mediaTypes]
  [mediaTypes."application/feed+json"]
    suffixes = ["json"]

[outputFormats.RSS]
baseName = "feed"
mediatype = "application/rss+xml"

[outputFormats.JSON]
baseName = "feed"
mediatype = "application/feed+json"

[outputFormats.SEARCH_JSON]
baseName = "index"
mediatype = "application/json"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[related]
  threshold = 50
  includeNewer = true
  toLower = true
  
  [[related.indices]]
    name = "keywords"
    weight = 100
  [[related.indices]]
    name = "tags"
    weight = 80
  [[related.indices]]
    name = "categories"
    weight = 60
  [[related.indices]]
    name = "description"
    weight = 40
  [[related.indices]]
    name = "title"
    weight = 20
  [[related.indices]]
    name = "date"
    weight = 10

[module]
  [module.hugoVersion]
    extended = true
    min = "0.125.0"

[params]
  google_analytics_id = "G-D12EVXX422"
  twitter_handle = "@stephenajulu"
  creator = "stephenajulu"
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showIntroContentOnHomepage = true
  showPostsOnHomepage = true
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addDot = true
  addFrame = false
  highlightColor = '#6320d6' #66320d6
  baseColor = "#030712" #ffffff
  baseOffsetColor = "#eaeaea"
  headingColor = "#ffffff" #000000
  textColor = "#ffffff" #4e5157
  dotColor = "#6320d6"
  enableGoogleFonts = true 
  location = "Nairobi, Kenya"
  enableGitInfo = true
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Fraunces:ital,opsz,wght@0,9..144,100..900;1,9..144,100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
  fontFamilyHeading = "Fraunces"
  fontFamilyParagraph = "Poppins"
  fontFamilyMonospace = "monospace"
  formspree = "https://formspree.io/f/alunje73@gmail.com"
  copyright = "Stephen Ajulu"
  footerContent = "&copy; Stephen Ajulu  — <a href='/license/' style='font-weight:bold;'>CC BY-NC-SA 4.0</a>"
  showFullTextinJSONFeed = "true"
  image = "images/socialimage.webp"
  logo = "images/me.webp"

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
  [[menu.main]]
    name = "Services"
    identifier = "services"
    weight = 2
    url = "/services/"
  [[menu.main]]
    name = "Store"
    identifier = "store"
    weight = 3
    url = "/store/"
  [[menu.main]]
    name = "Blog"
    identifier = "blog"
    weight = 4
    url = "/posts/"
  [[menu.main]]
    name = "More"
    identifier = "more"
    weight = 5
  [[menu.main]]
    name = "Portfolio"
    parent = "more"
    weight = 1
    url = "/projects/"
  [[menu.main]]
    name = "Notes"
    parent = "more"
    weight = 2
    url = "/notes/"
  [[menu.main]]
    name = "About"
    parent = "more"
    weight = 3
    url = "/About/"
  [[menu.main]]
    name = "Contact"
    parent = "more"
    weight = 4
    url = "/contact/"
  [[menu.main]]
    name = "CV"
    parent = "more"
    weight = 5
    url = "/cv/"
